import Head from "next/head";
import Image from "next/image";
import classNames from "classnames/bind";
import styles from "../styles/Home.module.css";

const cl = classNames.bind(styles);

const links = ["About", "Skills", "Portfolio", "Contact"];

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Parallax Star */}
      <div className={cl("bg-landing")}></div>
      <div className={cl("bg-landing")}></div>
      <div className={cl("bg-landing")}></div>
      {/* END Parallax Star */}
      <header>
        <nav className="text-white flex justify-between max-w-screen-xl m-auto pt-9 pb-11 items-center">
          <div>
            <a
              href=""
              className="font-pacifico pb-2 text-4xl relative after:content-[''] after:absolute after:w-24 after:h-0.5 after:bottom-0 after:left-0 after:bg-white "
            >
              ngPoi
            </a>
          </div>
          <div>
            <ul className="flex gap-14 ">
              {links.map((link, index) => {
                return (
                  <li key={index}>
                    <a
                      href="#"
                      className="text-2xl pb-2 relative duration-200 after:content-[''] after:absolute after:w-full after:scale-x-0 after:h-0.5 after:bottom-0 after:left-0 after:bg-transparent hover:after:bg-cyan-100 hover:text-cyan-100 hover:after:duration-200 hover:after:scale-x-100"
                    >
                      {link}
                    </a>
                  </li>
                );
              })}
            </ul>
          </div>
        </nav>
        <section className="max-w-screen-xl m-auto">
          <div className="flex justify-between items-center">
            <div className="">
              <h1 className="text-2xl mb-4">HELLO, IM NGPOI</h1>
              <h2 className="text-5xl font-bold mb-5">
                FRONT-END WEB DEVELOPER
              </h2>
              <p className="text-lg mb-5">Welcome to my personal website!</p>
              <button className={cl("btn")}>Get CV</button>
            </div>
            <div className="">
              <Image
                width={635}
                height={629}
                alt="ngPoi"
                src="/images/hero-img.png"
              />
            </div>
          </div>
        </section>
      </header>
      <section className="max-w-screen-xl m-auto my-20">
        <h2 className="text-5xl mb-5">My story</h2>
        <div className="flex gap-16">
          <div className="flex-1">
            <p className="text-lg mb-8">
              I was born and raised in Vietnam. When I was 15, I came to America
              on my own as a transfer student. After graduating in Florida, I
              attended Rhodes College in Tennessee as a Computer Science
              student. The COVID-19 pandemic forced me to move to Seattle in
              2020 when I started my in-depth front-end programming journey.
            </p>
            <div className="py-6 px-8 shadow-orange-50 rounded-2xl border-white border-solid border">
              <h3 className="text-2xl">A little bit about me</h3>
              <p>
                In my free time, I like to watch Youtube and Netflix, and
                playing games. My favorite youtubers are Danny Gonzales and Drew
                Gooden (Go Greg and Little Stinkers!). Some games I usually play
                are Wild Rift, Clash of Clans, and League of Legends.
              </p>
            </div>
          </div>
          <div className={cl("sphere")}>
            <div className={cl("layer")}>
              <div className={cl("ambience")}></div>
            </div>
            <div className={cl("layer")}>
              <div className={cl("ocean-glare")}></div>
            </div>
            <div className={cl("layer","land")} ></div>
            <div className={cl("layer","clouds")} ></div>
            <div className={cl("layer","darkside")} ></div>
            <div className={cl("layer",)}>
              <div className={cl("edge",)}></div>
            </div>
            <div className={cl("layer")}>
              <div className={cl("glare")}></div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
